version: '3'

services:
  app:
    build:
      context: ./golang
    depends_on:
      db:
        condition: service_healthy


  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_USER: mysql
      MYSQL_PASSWORD: hogehoge
      MYSQL_DATABASE: oreno_ramen_db
    ports:
      - 13306:3306
    volumes:
      # - ./mysql/data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD